### ISSUE TITLE
Будет ли дальнейшее развитие?

### ISSUE THREAD

**Issue by evpix** [LeonisX/jSite-Watcher#1]
Данный софт заброшен и не будет развиваться?

**Comment by LeonisX** [comment]
Привет, проект не заброшен. Переключился на другие, более приоритетные направления. Помню, начал писать свой HTML-парсер, но он оказался очень трудоёмким, не уложился во временные рамки. Раньше весны не продолжу, высокая загруженность

**Comment by EvolutionPixG** [comment]
> 
> 
> Привет, проект не заброшен. Переключился на другие, более приоритетные направления. Помню, начал писать свой HTML-парсер, но он оказался очень трудоёмким, не уложился во временные рамки. Раньше весны не продолжу, высокая загруженность

Хорошо что не забросили. Проект полезный. Учитывая что из хорошего софта для слежения за изменением сайта есть только коммерческий платный софт.

PS. Расширениями для браузера пользоваться не всегда удобно(Update Scaner, Web Page Scaner и прочими). По этому выбор пал на ваш софт.
